extend type Assignment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Assignment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Assignment`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID! @fdc_generated(from: "Assignment.course", purpose: IMPLICIT_REF_FIELD)
}
extend type Course {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Course", purpose: IMPLICIT_KEY_FIELD)
}
extend type Enrollment {
  """
  ✨ Implicit foreign key field based on `Enrollment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Enrollment.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Enrollment`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID! @fdc_generated(from: "Enrollment.course", purpose: IMPLICIT_REF_FIELD)
}
extend type Event {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Event", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Event`.`creator`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  creatorId: UUID! @fdc_generated(from: "Event.creator", purpose: IMPLICIT_REF_FIELD)
}
extend type StudyGroup {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "StudyGroup", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `StudyGroup`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID! @fdc_generated(from: "StudyGroup.course", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
