type IngestedData @table(name: "ingested_data") {
  id: ID! @column(name: "id", primaryKey: true, default: "gen_random_uuid()")
  source: String! @column(name: "source")
  data: String! @column(name: "data")
  createdAt: Timestamp! @column(name: "created_at", default: "now()")
}

extend type Query {
 listIngestedData: [IngestedData!]! @query(kind: "SELECT")
}

input IngestedDataInput {
  source: String!
  data: String!
}

extend type Mutation {
 createIngestedData(
   data: IngestedDataInput!
 ): IngestedData! @mutation(kind: "INSERT")
}
