
type IngestedData @table(name: "ingested_data") {
  id: ID! @column(name: "id", primaryKey: true, default: "gen_random_uuid()")
  source: String! @column(name: "source")
  data: String! @column(name: "data")
  createdAt: Timestamp! @column(name: "created_at", default: "now()")
}

type Query {
  listIngestedData: [IngestedData!]! @query(kind: "SELECT")
}

type Mutation {
  createIngestedData(
    data: IngestedDataInput!
  ): IngestedData! @mutation(kind: "INSERT")
}
